version: "3.8"
services:
  sql-server:
    container_name: sql-server
    image: mcr.microsoft.com/azure-sql-edge
    ports:
      - "1433:1433"
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=Grasmaaier99!
